# gitee

Host gitee.com

HostName gitee.com

PreferredAuthentications publickey

IdentityFile ~/.ssh/gitee_id_rsa

Host github.com  
User 3538616223@qq.com  	//注册github的邮箱
Hostname ssh.github.com  
PreferredAuthentications publickey  
IdentityFile ~/.ssh/id_rsa  
Port 443
